dicoclasse = {   
    "C01" : "'Explosibles, explosible instable','Explosibles, division 1.1','Explosibles, division 1.2','Explosibles, division 1.3','Explosibles, division 1.4','Substances et mélanges autoréactifs, type A','Substances et mélanges autoréactifs, type B','Peroxydes organiques, type A','Peroxydes organiques, type B'",
    "C02" : "'Gaz inflammables, catégories 1, 2','Aérosols, catégories 1, 2','Liquides inflammables, catégories 1, 2, 3','Matières solides inflammables, catégories 1, 2','Substances et mélanges autoréactifs, types B, C, D, E, F','Liquides pyrophoriques, catégorie 1','Matières solides pyrophoriques, catégorie 1','Substances et mélanges auto-échauffants, catégories 1, 2','Substances et mélanges qui, au contact de l’eau, dégagent des gaz inflammables, catégories 1, 2, 3','Peroxydes organiques, types B, C, D, E, F'",
    "C03" : "'Gaz comburants, catégorie 1','Liquides comburants, catégorie 1','Liquides comburants, catégorie 2','Liquides comburants, catégorie 3','Matières solides comburantes, catégorie 1','Matières solides comburantes, catégorie 2','Matières solides comburantes, catégorie 3'",
    "C04" : "'gaz comprimés','gaz liquéfiés','gaz liquéfiés réfrigérés','gaz dissous'",
    "C05" : "'Substances ou mélanges corrosifs pour les métaux, catégorie 1','Corrosion cutanée/irritation cutanée, catégorie 1A','Corrosion cutanée/irritation cutanée, catégorie 1B','Corrosion cutanée/irritation cutanée, catégorie 1C','Lésions oculaires graves/irritation oculaire, catégorie 1'",
    "C06" : "'Toxicité aiguë par voie orale, catégorie 1,2,3', 'Toxicité aiguë par voie cutanée, catégorie 1,2,3','Toxicité aiguë par inhalation, catégorie 1,2,3'",
    "C07" : "' Toxicité aiguë par voie orale, catégorie 4','Toxicité aiguë par voie cutanée, catégorie 4','Toxicité aiguë par inhalation, catégorie 4','Corrosion cutanée/irritation cutanée, catégorie 2','Lésions oculaires graves/irritation oculaire, catégorie 2','Sensibilisation cutanée, catégories 1, 1A, 1B','Toxicité spécifique pour certains organes cibles - Exposition unique, catégorie 3','Dangereux pour la couche d'ozone, catégorie 1'",
    "C08" : "'Sensibilisation respiratoire, catégories 1, 1A, 1B','Mutagénicité sur les cellules germinales, catégorie 1A','Mutagénicité sur les cellules germinales, catégorie 1B','Mutagénicité sur les cellules germinales, catégorie 2','Cancérogénicité, catégorie 1A','Cancérogénicité, catégorie 1B','Cancérogénicité, catégorie 2','Toxicité pour la reproduction, catégorie 1A','Toxicité pour la reproduction, catégorie 1B','Toxicité pour la reproduction, catégorie 2','Toxicité spécifique pour certains organes cibles - Exposition unique, catégorie 1','Toxicité spécifique pour certains organes cibles - Exposition unique, catégorie 2','Toxicité spécifique pour certains organes cibles - Exposition répétée, catégorie 1','Toxicité spécifique pour certains organes cibles - Exposition répétée, catégorie 2','Danger par aspiration, catégorie 1'",
    "C09" : "'Danger pour le milieu aquatique, toxicité à court terme (aiguë), catégorie 1','Danger pour le milieu aquatique, toxicité à long terme (chronique), catégorie 1 et 2'",
    }




dicomention = {
    "H200": "Explosif instable",
    "H201": "Explosif : danger d'explosion en masse",
    "H202": "Explosif : danger sérieux de projection",
    "H203": "Explosif : danger d'incendie, d'effet de souffle ou de projection",
    "H204": "Danger d'incendie ou de projection",
    "H205": "Danger d'explosion en masse en cas d'incendie",
    "H220": "Gaz extrêmement inflammable",
    "H221": "Gaz inflammable",
    "H222": "Aérosol extrêmement inflammable",
    "H223": "Aérosol inflammable",
    "H224": "Liquide et vapeurs extrêmement inflammables",
    "H225": "Liquide et vapeurs très inflammables",
    "H226": "Liquide et vapeurs inflammables",
    "H227": "Liquide combustible",
    "H228": "Matière solide inflammable",
    "H229": "Récipient sous pression : peut éclater sous l'effet de la chaleur.",
    "H230": "Peut exploser même en l'absence d'air.",
    "H231": "Peut exploser même en l'absence d'air à une pression et/ou une température élevée(s).",
    "H240": "Peut exploser en cas d'échauffement",
    "H241": "Peut s'enflammer ou exploser en cas d'échauffement",
    "H242": "Peut s'enflammer en cas d'échauffement",
    "H250": "S'enflamme spontanément au contact de l'air",
    "H251": "Matière auto-échauffante; peut s'enflammer",
    "H252": "Matière auto-échauffante en grandes quantités; peut s'enflammer",
    "H260": "Dégage, au contact de l'eau, des gaz inflammables qui peuvent s'enflammer spontanément",
    "H261": "Dégage, au contact de l'eau, des gaz inflammables",
    "H270": "Peut provoquer ou aggraver un incendie; comburant",
    "H271": "Peut provoquer un incendie ou une explosion; comburant puissant",
    "H272": "Peut aggraver un incendie; comburant",
    "H280": "Contient un gaz sous pression; peut exploser sous l'effet de la chaleur",
    "H281": "Contient un gaz réfrigéré; peut causer des brûlures ou blessures cryogéniques",
    "H290": "Peut être corrosif pour les métaux",
    "H300": "Mortel en cas d'ingestion",
    "H301": "Toxique en cas d'ingestion",
    "H302": "Nocif en cas d'ingestion",
    "H304": "Peut être mortel en cas d'ingestion et de pénétration dans les voies respiratoires",
    "H310": "Mortel par contact cutané",
    "H311": "Toxique par contact cutané",
    "H312": "Nocif par contact cutané",
    "H314": "Provoque de graves brûlures de la peau et des lésions oculaires",
    "H315": "Provoque une irritation cutanée",
    "H317": "Peut provoquer une allergie cutanée",
    "H318": "Provoque des lésions oculaires graves",
    "H319": "Provoque une sévère irritation des yeux",
    "H330": "Mortel par inhalation",
    "H331": "Toxique par inhalation",
    "H332": "Nocif par inhalation",
    "H334": "Peut provoquer des symptômes allergiques ou d'asthme ou des difficultés respiratoires par inhalation",
    "H335": "Peut irriter les voies respiratoires",
    "H336": "Peut provoquer somnolence ou vertiges",
    "H340": "Peut induire des anomalies génétiques (indiquer la voie d'exposition s'il est formellement prouvé qu'aucune autre voie d'exposition ne conduit au même danger)",
    "H341": "Susceptible d'induire des anomalies génétiques (indiquer la voie d'exposition s'il est formellement prouvé qu'aucune autre voie d'exposition ne conduit au même danger)",
    "H350": "Peut provoquer le cancer (indiquer la voie d'exposition s'il est formellement prouvé qu'aucune autre voie d'exposition ne conduit au même danger)",
    "H350i": "Peut provoquer le cancer par inhalation.",
    "H351": "Susceptible de provoquer le cancer (indiquer la voie d'exposition s'il est formellement prouvé qu'aucune autre voie d'exposition ne conduit au même danger)",
    "H360": "Peut nuire à la fertilité ou au fœtus (indiquer l'effet s'il est connu) (indiquer la voie d'exposition s'il est formellement prouvé qu'aucune autre voie d'exposition ne conduit au même danger)",
    "H360D": "Peut nuire au fœtus.",
    "H360Df": "Peut nuire au fœtus. Susceptible de nuire à la fertilité.",
    "H360F": "Peut nuire à la fertilité.",
    "H360Fd": "Peut nuire à la fertilité. Susceptible de nuire au fœtus.",
    "H360FD": "Peut nuire à la fertilité. Peut nuire au fœtus.",
    "H361": "Susceptible de nuire à la fertilité ou au fœtus (indiquer l'effet s'il est connu) (indiquer la voie d'exposition s'il est formellement prouvé qu'aucune autre voie d'exposition ne conduit au même danger)",
    "H361d": "Susceptible de nuire au fœtus.",
    "H361f": "Susceptible de nuire à la fertilité.",
    "H361fd": "Susceptible de nuire à la fertilité. Susceptible de nuire au fœtus.",
    "H362": "Peut être nocif pour les bébés nourris au lait maternel",
    "H370": "Risque avéré d'effets graves pour les organes (ou indiquer tous les organes affectés, s'ils sont connus) (indiquer la voie d'exposition s'il est formellement prouvé qu'aucune autre voie d'exposition ne conduit au même danger)",
    "H371": "Risque présumé d'effets graves pour les organes (ou indiquer tous les organes affectés, s'ils sont connus) (indiquer la voie d'exposition s'il est formellement prouvé qu'aucune autre voie d'exposition ne conduit au même danger)",
    "H372": "Risque avéré d'effets graves pour les organes (indiquer tous les organes affectés, s'ils sont connus) à la suite d'expositions répétées ou d'une exposition prolongée (indiquer la voie d'exposition s'il est formellement prouvé qu'aucune autre voie d'exposition ne conduit au même danger)",
    "H373": "Risque présumé d'effets graves pour les organes (indiquer tous les organes affectés, s'ils sont connus) à la suite d'expositions répétées ou d'une exposition prolongée (indiquer la voie d'exposition s'il est formellement prouvé qu'aucune autre voie d'exposition ne conduit au même danger)",
    "H400": "Très toxique pour les organismes aquatiques",
    "H410": "Très toxique pour les organismes aquatiques, entraîne des effets à long terme",
    "H411": "Toxique pour les organismes aquatiques, entraîne des effets à long terme",
    "H412": "Nocif pour les organismes aquatiques, entraîne des effets à long terme",
    "H413": "Peut entraîner des effets néfastes à long terme pour les organismes aquatiques",
    "H420": "Nuit à la santé publique et à l’environnement en détruisant l’ozone dans la haute atmosphère",
    }
